# Milestone 1: Data Profiling

Profil awal dataset besar Indonesia menggunakan Polars LazyFrame dan DuckDB. Isi sumber serta deskripsi dataset pada `data/README.md` sebelum menjalankan notebook ini.

In [11]:
%pip install -U huggingface_hub polars duckdb

Collecting huggingface_hub
  Downloading huggingface_hub-2.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: polars in /opt/conda/lib/python3.13/site-packages (2.0.0)
Requirement already satisfied: duckdb in /opt/conda/lib/python3.13/site-packages (1.5.6)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /opt/conda/lib/python3.13/site-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /opt/conda/lib/python3.13/site-packages (from huggingface_hub) (4.2.4)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.13/site-packages (from huggingface_hub) (2026.9.0)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface_hub)
  Downloading hf_xet-1.7.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface_hub)
  Downloading httpx2-2.15.1-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: packaging>=20.9 in /opt/conda/lib/python3.13/site-packages (from huggingface_hub) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.13/site-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /opt/conda/lib/python3.13/site-packages (from huggingface_hub) (4.70.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.13/site-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: anyio>=4.10 in /opt/conda/lib/python3.13/site-packages (from httpx2<3,>=2.0.0->huggingface_hub) (4.15.1)
Collecting httpcore2==2.15.1 (from httpx2<3,>=2.0.0->huggingface_hub)
  Downloading httpcore2-2.15.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: idna>=3.18 in /opt/conda/lib/python3.13/site-packages (from httpx2<3,>=2.0.0->huggingface_hub) (3.20)
Requirement already satisfied: truststore>=0.10 in /opt/conda/lib/python3.13/site-packages (from httpx2<3,>=2.0.0->huggingface_hub) (0.10.5)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.13/site-packages (from httpcore2==2.15.1->httpx2<3,>=2.0.0->huggingface_hub) (0.16.0)
Requirement already satisfied: polars-runtime-32==2.0.0 in /opt/conda/lib/python3.13/site-packages (from polars) (2.0.0)
Downloading huggingface_hub-2.2.0-py3-none-any.whl (839 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 839.9/839.9 kB 1.6 MB/s  0:00:00 eta 0:00:01
Downloading hf_xet-1.7.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 1.6 MB/s  0:00:02 eta 0:00:01
Downloading httpx2-2.15.1-py3-none-any.whl (96 kB)
Downloading httpcore2-2.15.1-py3-none-any.whl (85 kB)
Installing collected packages: httpcore2, hf-xet, httpx2, huggingface_hub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [huggingface_hub] [huggingface_hub]
Successfully installed hf-xet-1.7.0 httpcore2-2.15.1 httpx2-2.15.1 huggingface_hub-2.2.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
from pathlib import Path
from huggingface_hub import HfApi, hf_hub_download

PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
RAW_DIR.mkdir(parents=True, exist_ok=True)

REPO_ID = "IndonesiaAI/cleaned-data-split-0"

api = HfApi()
files = api.list_repo_files(repo_id=REPO_ID, repo_type="dataset")

parquet_files = [f for f in files if f.endswith(".parquet")]
print("File Parquet yang tersedia di repositori:")
for f in parquet_files:
    print("-", f)

File Parquet yang tersedia di repositori:
- data/train-00000-of-00006-042e4a2154d9270b.parquet
- data/train-00001-of-00006-8666365fa80b1ec5.parquet
- data/train-00002-of-00006-8ac9b553e82a7f8f.parquet
- data/train-00003-of-00006-25183230856f688a.parquet
- data/train-00004-of-00006-a7a9cb4b60d46e79.parquet
- data/train-00005-of-00006-a7fd9cf190643493.parquet

In [1]:
import os

# Kurangi masalah pada progres interaktif dan jalur unduhan Xet
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
os.environ["HF_HUB_DISABLE_XET"] = "1"

from pathlib import Path
from huggingface_hub import HfApi, hf_hub_download

PROJECT_ROOT = Path("/home/jovyan/work")
RAW_DIR = PROJECT_ROOT / "data" / "raw"
RAW_DIR.mkdir(parents=True, exist_ok=True)

REPO_ID = "IndonesiaAI/cleaned-data-split-0"

api = HfApi()
files = api.list_repo_files(repo_id=REPO_ID, repo_type="dataset")
parquet_files = sorted(f for f in files if f.endswith(".parquet"))

print("Jumlah file Parquet yang ditemukan:", len(parquet_files))
for f in parquet_files:
    print(f)

Jumlah file Parquet yang ditemukan: 6
data/train-00000-of-00006-042e4a2154d9270b.parquet
data/train-00001-of-00006-8666365fa80b1ec5.parquet
data/train-00002-of-00006-8ac9b553e82a7f8f.parquet
data/train-00003-of-00006-25183230856f688a.parquet
data/train-00004-of-00006-a7a9cb4b60d46e79.parquet
data/train-00005-of-00006-a7fd9cf190643493.parquet

In [2]:
for i, filename in enumerate(parquet_files, start=1):
    print(f"[{i}/{len(parquet_files)}] Mengunduh: {filename}")

    downloaded_path = hf_hub_download(
        repo_id=REPO_ID,
        filename=filename,
        repo_type="dataset",
        local_dir=RAW_DIR,
    )

    print("Selesai:", downloaded_path)

[1/6] Mengunduh: data/train-00000-of-00006-042e4a2154d9270b.parquet

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Selesai: /home/jovyan/work/data/raw/data/train-00000-of-00006-042e4a2154d9270b.parquet
[2/6] Mengunduh: data/train-00001-of-00006-8666365fa80b1ec5.parquet
Selesai: /home/jovyan/work/data/raw/data/train-00001-of-00006-8666365fa80b1ec5.parquet
[3/6] Mengunduh: data/train-00002-of-00006-8ac9b553e82a7f8f.parquet
Selesai: /home/jovyan/work/data/raw/data/train-00002-of-00006-8ac9b553e82a7f8f.parquet
[4/6] Mengunduh: data/train-00003-of-00006-25183230856f688a.parquet
Selesai: /home/jovyan/work/data/raw/data/train-00003-of-00006-25183230856f688a.parquet
[5/6] Mengunduh: data/train-00004-of-00006-a7a9cb4b60d46e79.parquet
Selesai: /home/jovyan/work/data/raw/data/train-00004-of-00006-a7a9cb4b60d46e79.parquet
[6/6] Mengunduh: data/train-00005-of-00006-a7fd9cf190643493.parquet
Selesai: /home/jovyan/work/data/raw/data/train-00005-of-00006-a7fd9cf190643493.parquet

In [3]:
parquet_files_local = sorted(RAW_DIR.rglob("*.parquet"))

print("Jumlah file lokal:", len(parquet_files_local))

for f in parquet_files_local:
    print(f"{f.name}: {f.stat().st_size / 1_000_000:.2f} MB")

Jumlah file lokal: 6
train-00000-of-00006-042e4a2154d9270b.parquet: 153.50 MB
train-00001-of-00006-8666365fa80b1ec5.parquet: 153.29 MB
train-00002-of-00006-8ac9b553e82a7f8f.parquet: 151.92 MB
train-00003-of-00006-25183230856f688a.parquet: 152.17 MB
train-00004-of-00006-a7a9cb4b60d46e79.parquet: 152.67 MB
train-00005-of-00006-a7fd9cf190643493.parquet: 152.77 MB

In [6]:
from pathlib import Path
import duckdb
import polars as pl

# Tentukan lokasi proyek secara langsung
PROJECT_ROOT = Path("/home/jovyan/work")
RAW_DIR = PROJECT_ROOT / "data" / "raw"

# Cari file Parquet di folder raw dan seluruh subfoldernya
PARQUET_FILES = sorted(RAW_DIR.rglob("*.parquet"))

print("Lokasi folder raw:", RAW_DIR)
print("Folder tersedia:", RAW_DIR.exists())
print("Jumlah file Parquet:", len(PARQUET_FILES))

if not PARQUET_FILES:
    raise FileNotFoundError(
        f"File Parquet belum ditemukan di {RAW_DIR}. "
        "Pastikan proses unduhan sudah selesai."
    )

for file in PARQUET_FILES:
    print(f"{file.name} | {file.stat().st_size / 1_000_000:.2f} MB")

# Membaca semua file Parquet
df = pl.scan_parquet([str(file) for file in PARQUET_FILES])

print("\nSkema dataset:")
print(df.collect_schema())

print("\nLima baris pertama:")
display(df.head(5).collect())

Lokasi folder raw: /home/jovyan/work/data/raw
Folder tersedia: True
Jumlah file Parquet: 6
train-00000-of-00006-042e4a2154d9270b.parquet | 153.50 MB
train-00001-of-00006-8666365fa80b1ec5.parquet | 153.29 MB
train-00002-of-00006-8ac9b553e82a7f8f.parquet | 151.92 MB
train-00003-of-00006-25183230856f688a.parquet | 152.17 MB
train-00004-of-00006-a7a9cb4b60d46e79.parquet | 152.67 MB
train-00005-of-00006-a7fd9cf190643493.parquet | 152.77 MB

Skema dataset:
Schema({'qid': Int64, 'question': String, 'date': String, 'metadata': List(String), 'response_j': String, 'response_k': String})

Lima baris pertama:

shape: (5, 6)
┌───────┬───────────────────┬────────────┬───────────────────┬──────────────────┬──────────────────┐
│ qid   ┆ question          ┆ date       ┆ metadata          ┆ response_j       ┆ response_k       │
│ ---   ┆ ---               ┆ ---        ┆ ---               ┆ ---              ┆ ---              │
│ i64   ┆ str               ┆ str        ┆ list[str]         ┆ str              ┆ str              │
╞═══════╪═══════════════════╪════════════╪═══════════════════╪══════════════════╪══════════════════╡
│ 26351 ┆ I was studying    ┆ 2016/03/23 ┆ ["https://aviatio ┆ Lets start with  ┆ For those        │
│       ┆ for icing and a…  ┆            ┆ n.stackexchan…    ┆ the very basic…  ┆ recommended      │
│       ┆                   ┆            ┆                   ┆                  ┆ actions …        │
│ 26351 ┆ I was studying    ┆ 2016/03/23 ┆ ["https://aviatio ┆ Lets start with  ┆ I have a theory  │
│       ┆ for icing and a…  ┆            ┆ n.stackexchan…    ┆ the very basic…  ┆ on applying th…  │
│ 77133 ┆ There seems to be ┆ 2009/11/30 ┆ ["https://superus ┆ OK, hopefully    ┆ If you want      │
│       ┆ a lot of sof…     ┆            ┆ er.com/questi…    ┆ supplying a      ┆ something where  │
│       ┆                   ┆            ┆                   ┆ *use…            ┆ yo…              │
│ 77133 ┆ There seems to be ┆ 2009/11/30 ┆ ["https://superus ┆ If you're on     ┆ If you want      │
│       ┆ a lot of sof…     ┆            ┆ er.com/questi…    ┆ Windows, what    ┆ something where  │
│       ┆                   ┆            ┆                   ┆ abo…             ┆ yo…              │
│ 77133 ┆ There seems to be ┆ 2009/11/30 ┆ ["https://superus ┆ OK, hopefully    ┆ If you're on     │
│       ┆ a lot of sof…     ┆            ┆ er.com/questi…    ┆ supplying a      ┆ Windows, what    │
│       ┆                   ┆            ┆                   ┆ *use…            ┆ abo…             │
└───────┴───────────────────┴────────────┴───────────────────┴──────────────────┴──────────────────┘

## Profil Polars

`scan_parquet` hanya membangun rencana query; file baru dibaca ketika `collect()` dipanggil.

In [8]:
from pathlib import Path
import polars as pl

# Lokasi dataset yang benar
RAW_DIR = Path("/home/jovyan/work/data/raw")

# Cari file Parquet di dalam folder dan subfolder
PARQUET_FILES = sorted(RAW_DIR.rglob("*.parquet"))

print("Folder dataset:", RAW_DIR)
print("Folder tersedia:", RAW_DIR.exists())
print("Jumlah file:", len(PARQUET_FILES))

if not PARQUET_FILES:
    raise FileNotFoundError(
        "Belum ada file Parquet. Periksa proses unduhan dataset."
    )

# Baca seluruh file Parquet sebagai satu dataset
lazy_data = pl.scan_parquet([str(file) for file in PARQUET_FILES])

print("\nSkema dataset:")
print(lazy_data.collect_schema())

print("\nLima baris pertama:")
display(lazy_data.head(5).collect())

Folder dataset: /home/jovyan/work/data/raw
Folder tersedia: True
Jumlah file: 6

Skema dataset:
Schema({'qid': Int64, 'question': String, 'date': String, 'metadata': List(String), 'response_j': String, 'response_k': String})

Lima baris pertama:

shape: (5, 6)
┌───────┬───────────────────┬────────────┬───────────────────┬──────────────────┬──────────────────┐
│ qid   ┆ question          ┆ date       ┆ metadata          ┆ response_j       ┆ response_k       │
│ ---   ┆ ---               ┆ ---        ┆ ---               ┆ ---              ┆ ---              │
│ i64   ┆ str               ┆ str        ┆ list[str]         ┆ str              ┆ str              │
╞═══════╪═══════════════════╪════════════╪═══════════════════╪══════════════════╪══════════════════╡
│ 26351 ┆ I was studying    ┆ 2016/03/23 ┆ ["https://aviatio ┆ Lets start with  ┆ For those        │
│       ┆ for icing and a…  ┆            ┆ n.stackexchan…    ┆ the very basic…  ┆ recommended      │
│       ┆                   ┆            ┆                   ┆                  ┆ actions …        │
│ 26351 ┆ I was studying    ┆ 2016/03/23 ┆ ["https://aviatio ┆ Lets start with  ┆ I have a theory  │
│       ┆ for icing and a…  ┆            ┆ n.stackexchan…    ┆ the very basic…  ┆ on applying th…  │
│ 77133 ┆ There seems to be ┆ 2009/11/30 ┆ ["https://superus ┆ OK, hopefully    ┆ If you want      │
│       ┆ a lot of sof…     ┆            ┆ er.com/questi…    ┆ supplying a      ┆ something where  │
│       ┆                   ┆            ┆                   ┆ *use…            ┆ yo…              │
│ 77133 ┆ There seems to be ┆ 2009/11/30 ┆ ["https://superus ┆ If you're on     ┆ If you want      │
│       ┆ a lot of sof…     ┆            ┆ er.com/questi…    ┆ Windows, what    ┆ something where  │
│       ┆                   ┆            ┆                   ┆ abo…             ┆ yo…              │
│ 77133 ┆ There seems to be ┆ 2009/11/30 ┆ ["https://superus ┆ OK, hopefully    ┆ If you're on     │
│       ┆ a lot of sof…     ┆            ┆ er.com/questi…    ┆ supplying a      ┆ Windows, what    │
│       ┆                   ┆            ┆                   ┆ *use…            ┆ abo…             │
└───────┴───────────────────┴────────────┴───────────────────┴──────────────────┴──────────────────┘

In [9]:
contoh_data = lazy_data.head(10).collect()
contoh_data

shape: (10, 6)
┌─────────┬──────────────────┬────────────┬──────────────────┬──────────────────┬──────────────────┐
│ qid     ┆ question         ┆ date       ┆ metadata         ┆ response_j       ┆ response_k       │
│ ---     ┆ ---              ┆ ---        ┆ ---              ┆ ---              ┆ ---              │
│ i64     ┆ str              ┆ str        ┆ list[str]        ┆ str              ┆ str              │
╞═════════╪══════════════════╪════════════╪══════════════════╪══════════════════╪══════════════════╡
│ 26351   ┆ I was studying   ┆ 2016/03/23 ┆ ["https://aviati ┆ Lets start with  ┆ For those        │
│         ┆ for icing and a… ┆            ┆ on.stackexchan…  ┆ the very basic…  ┆ recommended      │
│         ┆                  ┆            ┆                  ┆                  ┆ actions …        │
│ 26351   ┆ I was studying   ┆ 2016/03/23 ┆ ["https://aviati ┆ Lets start with  ┆ I have a theory  │
│         ┆ for icing and a… ┆            ┆ on.stackexchan…  ┆ the very basic…  ┆ on applying th…  │
│ 77133   ┆ There seems to   ┆ 2009/11/30 ┆ ["https://superu ┆ OK, hopefully    ┆ If you want      │
│         ┆ be a lot of sof… ┆            ┆ ser.com/questi…  ┆ supplying a      ┆ something where  │
│         ┆                  ┆            ┆                  ┆ *use…            ┆ yo…              │
│ 77133   ┆ There seems to   ┆ 2009/11/30 ┆ ["https://superu ┆ If you're on     ┆ If you want      │
│         ┆ be a lot of sof… ┆            ┆ ser.com/questi…  ┆ Windows, what    ┆ something where  │
│         ┆                  ┆            ┆                  ┆ abo…             ┆ yo…              │
│ 77133   ┆ There seems to   ┆ 2009/11/30 ┆ ["https://superu ┆ OK, hopefully    ┆ If you're on     │
│         ┆ be a lot of sof… ┆            ┆ ser.com/questi…  ┆ supplying a      ┆ Windows, what    │
│         ┆                  ┆            ┆                  ┆ *use…            ┆ abo…             │
│ 8499    ┆ I am writing an  ┆ 2013/05/30 ┆ ["https://crypto ┆ If a user has a  ┆ Your master      │
│         ┆ application, r…  ┆            ┆ .stackexchange…  ┆ copy of both t…  ┆ secret is        │
│         ┆                  ┆            ┆                  ┆                  ┆ **never*…        │
│ 2055713 ┆ In his book "Men ┆ 2016/12/12 ┆ ["https://math.s ┆ 1. Feller's      ┆ It's a bit more  │
│         ┆ of Mathematic…   ┆            ┆ tackexchange.c…  ┆ first volume for ┆ advanced than …  │
│         ┆                  ┆            ┆                  ┆ P…               ┆                  │
│ 2055713 ┆ In his book "Men ┆ 2016/12/12 ┆ ["https://math.s ┆ I don’t agree    ┆ It's a bit more  │
│         ┆ of Mathematic…   ┆            ┆ tackexchange.c…  ┆ with Bell on     ┆ advanced than …  │
│         ┆                  ┆            ┆                  ┆ thi…             ┆                  │
│ 2055713 ┆ In his book "Men ┆ 2016/12/12 ┆ ["https://math.s ┆ 1. Feller's      ┆ In the early     │
│         ┆ of Mathematic…   ┆            ┆ tackexchange.c…  ┆ first volume for ┆ '70s, I used two │
│         ┆                  ┆            ┆                  ┆ P…               ┆ …                │
│ 2055713 ┆ In his book "Men ┆ 2016/12/12 ┆ ["https://math.s ┆ I don’t agree    ┆ 1. Feller's      │
│         ┆ of Mathematic…   ┆            ┆ tackexchange.c…  ┆ with Bell on     ┆ first volume for │
│         ┆                  ┆            ┆                  ┆ thi…             ┆ P…               │
└─────────┴──────────────────┴────────────┴──────────────────┴──────────────────┴──────────────────┘

## Profil DuckDB

DuckDB membaca file Parquet langsung dari disk dan menghasilkan ringkasan statistik setiap kolom.

In [11]:
from pathlib import Path
import duckdb

# Lokasi folder dataset
RAW_DIR = Path("/home/jovyan/work/data/raw")

# Cari seluruh file Parquet
parquet_files = sorted(RAW_DIR.rglob("*.parquet"))

if not parquet_files:
    raise FileNotFoundError(
        f"Tidak ditemukan file Parquet di {RAW_DIR}. "
        "Pastikan unduhan dataset sudah selesai."
    )

print(f"Jumlah file ditemukan: {len(parquet_files)}")

# Hubungkan ke DuckDB
connection = duckdb.connect()

# Baca file Parquet langsung dari disk
profil_duckdb = connection.execute(
    "SUMMARIZE SELECT * FROM read_parquet(?)",
    [[str(file) for file in parquet_files]]
).pl()

display(profil_duckdb)

Jumlah file ditemukan: 6

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (6, 12)
┌─────────────┬─────────────┬────────────┬────────────┬───┬────────┬────────┬─────────┬────────────┐
│ column_name ┆ column_type ┆ min        ┆ max        ┆ … ┆ q50    ┆ q75    ┆ count   ┆ null_perce │
│ ---         ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---    ┆ ---     ┆ ntage      │
│ str         ┆ str         ┆ str        ┆ str        ┆   ┆ str    ┆ str    ┆ i64     ┆ ---        │
│             ┆             ┆            ┆            ┆   ┆        ┆        ┆         ┆ decimal[9, │
│             ┆             ┆            ┆            ┆   ┆        ┆        ┆         ┆ 2]         │
╞═════════════╪═════════════╪════════════╪════════════╪═══╪════════╪════════╪═════════╪════════════╡
│ qid         ┆ BIGINT      ┆ 1          ┆ 74661602   ┆ … ┆ 105289 ┆ 457156 ┆ 1050257 ┆ 0.00       │
│ question    ┆ VARCHAR     ┆ !!! I      ┆ ﻿ What      ┆ … ┆ null   ┆ null   ┆ 1050257 ┆ 0.00       │
│             ┆             ┆ found an   ┆ would a    ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆ interestin ┆ political  ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆ g sol…     ┆ syste…     ┆   ┆        ┆        ┆         ┆            │
│ date        ┆ VARCHAR     ┆ 2008/08/01 ┆ 2023/03/04 ┆ … ┆ null   ┆ null   ┆ 1050257 ┆ 0.00       │
│ metadata    ┆ VARCHAR[]   ┆ ['https:// ┆ ['https:// ┆ … ┆ null   ┆ null   ┆ 1050257 ┆ 0.00       │
│             ┆             ┆ 3dprinting ┆ writers.st ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆ .meta.stac ┆ ackexchang ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆ …          ┆ …          ┆   ┆        ┆        ┆         ┆            │
│ response_j  ┆ VARCHAR     ┆            ┆ ﷲ          ┆ … ┆ null   ┆ null   ┆ 1050257 ┆ 0.00       │
│             ┆             ┆            ┆ =          ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆            ┆            ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆            ┆ الله       ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆            ┆ ====       ┆   ┆        ┆        ┆         ┆            │
│ response_k  ┆ VARCHAR     ┆ !          ┆ Watch     ┆ … ┆ null   ┆ null   ┆ 1050257 ┆ 0.00       │
│             ┆             ┆            ┆ only       ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆ Just as    ┆ produces   ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆ well that  ┆ notificat… ┆   ┆        ┆        ┆         ┆            │
│             ┆             ┆ I have a…  ┆            ┆   ┆        ┆        ┆         ┆            │
└─────────────┴─────────────┴────────────┴────────────┴───┴────────┴────────┴─────────┴────────────┘

## Catatan Milestone 1

Tulis temuan awal di bawah ini: ukuran data, jumlah baris, tipe kolom, kolom dengan null terbanyak, serta anomali yang perlu ditangani pada Milestone 2.

## Catatan Milestone 1

### 1. Ukuran Data
Dataset yang digunakan adalah **IndonesiaAI - cleaned-data-split-0** dari platform Hugging Face Datasets, dengan split `train` dan format Parquet. Dataset terdiri dari 6 file Parquet yang disimpan di direktori `data/raw/`. Berdasarkan informasi dataset, ukuran penyimpanan lokalnya sekitar **874 MB**.

### 2. Jumlah Baris
Dataset memiliki sekitar **1.050.257 baris**. Jumlah tersebut telah memenuhi persyaratan tugas Analisis Big Data, yaitu lebih dari 1 juta baris.

### 3. Tipe Kolom
Dataset berisi data teks dan metadata. Berdasarkan contoh struktur dataset, kolom yang tersedia meliputi `qid`, `question`, `date`, `metadata`, `response_j`, dan `response_k`. Tipe data aktual setiap kolom akan dikonfirmasi melalui profiling menggunakan Polars dan DuckDB.

### 4. Kolom dengan Null Terbanyak
Jumlah nilai null pada setiap kolom belum ditetapkan karena hasil profiling aktual masih perlu diperiksa. Pemeriksaan dilakukan untuk mengetahui kolom yang memiliki nilai kosong terbanyak sehingga dapat ditentukan prioritas penanganannya pada Milestone 2.

### 5. Anomali yang Perlu Ditangani pada Milestone 2
Beberapa aspek yang perlu diperiksa lebih lanjut meliputi:
- Nilai null atau data kosong pada kolom teks dan metadata.
- Baris duplikat yang berpotensi memengaruhi hasil analisis.
- Konsistensi format tanggal pada kolom `date`.
- Ketidaksesuaian tipe data atau format isi kolom.
- Konsistensi isi teks pada kolom `question`, `response_j`, dan `response_k`.

Temuan tersebut merupakan aspek pemeriksaan yang direncanakan, bukan anomali yang sudah dipastikan ditemukan.

### 6. Rencana Milestone 2
Pada Milestone 2, data akan diprofilkan dan dibersihkan menggunakan Polars, sedangkan DuckDB digunakan untuk menghasilkan ringkasan statistik setiap kolom melalui perintah `SUMMARIZE`. Penanganan nilai kosong, duplikat, dan format tanggal akan dilakukan berdasarkan hasil pemeriksaan agar data tetap sesuai dengan tujuan analisis.

### Kesimpulan
Dataset IndonesiaAI - cleaned-data-split-0 dipilih karena memiliki lebih dari satu juta baris dan tersedia dalam format Parquet. Dataset ini akan digunakan untuk mempelajari karakteristik data, mengevaluasi kualitas data, dan melakukan proses pembersihan sebelum analisis lanjutan.